"""Curated canonical mappings for Coverage Sprint v0.2."""

from __future__ import annotations

import re

# raw -> (canonical, slot)
V02_MAPPINGS: dict[str, tuple[str, str]] = {
    # BOOM auto-generated Chinese
    "嘶叫": ("Shriek", "action"),
    "饥饿": ("Hungry", "detail"),
    "松果": ("Pinecone", "object"),
    "魔鬼": ("Devil", "source"),
    "僵尸": ("Zombie", "source"),
    "向上": ("Upwards", "modifier"),
    "缓慢": ("Slow", "detail"),
    "铃声": ("Chime", "detail"),
    "轰鸣": ("Rumble", "detail"),
    "等离子": ("Plasma", "source"),
    "反弹": ("Rebound", "action"),
    "溪流": ("Stream", "source"),
    "潺潺": ("Flow", "action"),
    "远近": ("Close Far", "modifier"),
    "混合": ("Mixed", "modifier"),
    # Recording filename tokens (Chinese)
    "摔倒": ("Fall", "action"),
    "滚动": ("Rolling", "action"),
    "空心": ("Hollow", "detail"),
    "相互": ("Mutual", "detail"),
    "圆形": ("Round", "detail"),
    "返回": ("Back", "modifier"),
    "稳定": ("Steady", "detail"),
    "颗粒": ("Granular", "detail"),
    "沉重": ("Heavy", "detail"),
    "闷响": ("Muted", "detail"),
    "叮当": ("Clink", "detail"),
    "易碎": ("Brittle", "detail"),
    "碰撞": ("Collision", "action"),
    "火炬": ("Fire Torch", "source"),
    "燃烧": ("Burn", "action"),
    "石块": ("Rock Block", "object"),
    "洞口": ("Cave Mouth", "modifier"),
    "尖叫": ("Screech", "action"),
    "按压": ("Press", "action"),
    "冰砖": ("Ice Brick", "object"),
    "冰斧": ("Ice Axe", "object"),
    "玻璃球": ("Glass Ball", "object"),
    "拧": ("Screw", "action"),
    "拍": ("Pat", "action"),
    "水晶": ("Crystal", "object"),
    "高频": ("High Frequency", "detail"),
    "颗粒感": ("Gritty", "detail"),
    "余响": ("Ringout", "detail"),
    "分层": ("Layer", "detail"),
    "薄": ("Thin", "detail"),
    "咬": ("Bite", "action"),
    "扎": ("Prick", "action"),
    "郁金香": ("Tulip", "object"),
    # English tokens from recordings / mixed
    "Watermelon": ("Watermelon", "source"),
    "TungstenCarbide": ("Tungsten Carbide", "material"),
    "Handwheel": ("Handwheel", "object"),
    "MED": ("Medium", "modifier"),
    "CLS": ("Close", "modifier"),
    "SHT": ("Short", "modifier"),
    "LG": ("Large", "detail"),
    "Cabbage": ("Cabbage", "source"),
    "Mid": ("Medium", "detail"),
    "RubberRod": ("Rubber Rod", "object"),
    "Left": ("Left", "modifier"),
    "Right": ("Right", "modifier"),
    "Dampened": ("Dampened", "detail"),
    "Handrail": ("Handrail", "object"),
    "Lower": ("Lower", "modifier"),
    "Multiple": ("Multiple", "detail"),
    "Mutual": ("Mutual", "detail"),
    "OnSelf": ("On Self", "detail"),
    "GLASSBALL": ("Glass Ball", "object"),
    "Swrod": ("Sword", "object"),
    "Ringout": ("Ringout", "detail"),
    "Crowbar": ("Crowbar", "object"),
    "UnSheath": ("Unsheath", "action"),
    "Sheath": ("Sheath", "object"),
    "Ninja": ("Ninja", "modifier"),
    "ArcadeButton": ("Arcade Button", "object"),
    "ArcadeStick": ("Arcade Stick", "object"),
    "Sign": ("Sign", "object"),
    "WINDSINGER": ("Wind Singer", "source"),
    "Backward": ("Backward", "modifier"),
    "Forward": ("Forward", "modifier"),
    "BubbleWarp": ("Bubble Wrap", "material"),
    "CabinetFriction": ("Cabinet Friction", "action"),
    "ThickEnd": ("Thick End", "detail"),
    "Layer": ("Layer", "detail"),
    "LITESOUND": ("Lite Sound", "source"),
    "Src": ("Source", "modifier"),
    "Lee": ("Lee", "modifier"),
    "Prick": ("Prick", "action"),
    "Tulip": ("Tulip", "object"),
    "Constant": ("Constant", "detail"),
    "Handed": ("Handed", "detail"),
    "Two": ("Two", "detail"),
    "Gnarly": ("Gnarly", "detail"),
    "Driven": ("Driven", "detail"),
    "Madness": ("Madness", "detail"),
    "Paving": ("Paving", "detail"),
    "Carronade": ("Carronade", "source"),
    "Extinguish": ("Extinguish", "action"),
    "Upwards": ("Upwards", "modifier"),
    "Playful": ("Playful", "detail"),
    "Clavier": ("Clavier", "object"),
    "Eternal": ("Eternal", "modifier"),
    "Inch": ("Inch", "detail"),
    "Horizontal": ("Horizontal", "detail"),
    "iridium": ("Iridium", "material"),
    "Snarl": ("Snarl", "action"),
    "Greasy": ("Greasy", "detail"),
    "Alerted": ("Alerted", "detail"),
    "Ithaca": ("Ithaca", "modifier"),
    "Dragunov": ("Dragunov", "modifier"),
    "PSL": ("PSL", "modifier"),
    "Unequip": ("Unequip", "action"),
    "Progressive": ("Progressive", "modifier"),
    "Gesture": ("Gesture", "action"),
    "Filter": ("Filter", "detail"),
    "Rubbery": ("Rubbery", "detail"),
    "Last": ("Last", "modifier"),
    "Webley": ("Webley", "modifier"),
    "Mk": ("Mk", "modifier"),
    "Vi": ("Vi", "modifier"),
    "Dryfire": ("Dryfire", "action"),
    "DP": ("DP", "modifier"),
    "PPD": ("PPD", "modifier"),
    "Tokarev": ("Tokarev", "modifier"),
    "SVT": ("SVT", "modifier"),
    "Mark": ("Mark", "modifier"),
    "II": ("II", "modifier"),
    "0.5kg": ("0.5kg", "detail"),
    # Mixed fantasy / sci-fi English
    "mana": ("Mana", "source"),
    "void": ("Void", "source"),
    "core": ("Core", "object"),
    "demon": ("Demon", "source"),
    "overload": ("Overload", "action"),
    "overcharge": ("Overcharge", "action"),
    "fail": ("Fail", "action"),
    "HUD": ("HUD", "object"),
    "rebound": ("Rebound", "action"),
    "implant": ("Implant", "object"),
    "achievement": ("Achievement", "detail"),
    "cybernetic": ("Cybernetic", "modifier"),
    "capacitor": ("Capacitor", "object"),
    "discharge": ("Discharge", "action"),
    "distortion": ("Distortion", "detail"),
    "static": ("Static", "detail"),
    "zap": ("Zap", "action"),
    "chirp": ("Chirp", "action"),
    "buzz": ("Buzz", "detail"),
    "beep": ("Beep", "detail"),
    "pulse": ("Pulse", "detail"),
    "warp": ("Warp", "detail"),
    "ripple": ("Ripple", "detail"),
    "travel": ("Travel", "action"),
    "clash": ("Clash", "action"),
    "toll": ("Toll", "action"),
    "fireball": ("Fireball", "object"),
    "fence": ("Fence", "object"),
    "beam": ("Beam", "object"),
    "alert": ("Alert", "detail"),
    "menu": ("Menu", "object"),
    "select": ("Select", "action"),
    "confirm": ("Confirm", "action"),
    "unlock": ("Unlock", "action"),
    "teleport": ("Teleport", "action"),
    "glow": ("Glow", "detail"),
    "warning": ("Warning", "detail"),
    "rifle": ("Rifle", "object"),
    "barrier": ("Barrier", "object"),
    "frost": ("Frost", "modifier"),
    "lightning": ("Lightning", "source"),
    "circle": ("Circle", "object"),
    "vacuum": ("Vacuum", "modifier"),
    "storm": ("Storm", "source"),
    "whir": ("Whir", "detail"),
    "roar": ("Roar", "action"),
    "howl": ("Howl", "action"),
    "growl": ("Growl", "action"),
    "shadow": ("Shadow", "modifier"),
    "error": ("Error", "detail"),
    "deflect": ("Deflect", "action"),
    "spark": ("Spark", "source"),
    "drain": ("Drain", "action"),
    "shimmer": ("Shimmer", "detail"),
    "crackle": ("Crackle", "detail"),
    "sweep": ("Sweep", "action"),
    "plasma": ("Plasma", "source"),
    "electric": ("Electric", "modifier"),
    "arcane": ("Arcane", "modifier"),
    "magic": ("Magic", "source"),
    "portal": ("Portal", "source"),
    "rune": ("Rune", "source"),
    "shield": ("Shield", "object"),
    "ui": ("UI", "object"),
    "creature": ("Creature", "source"),
    "energy": ("Energy", "source"),
    "glitch": ("Glitch", "detail"),
    "cyber": ("Cyber", "modifier"),
    "anvil": ("Anvil", "object"),
    "dragon": ("Dragon", "source"),
    "ghost": ("Ghost", "source"),
    "crystal": ("Crystal", "object"),
    "thunder": ("Thunder", "source"),
    "laser": ("Laser", "source"),
    "holy": ("Holy", "modifier"),
    "alien": ("Alien", "source"),
    "robot": ("Robot", "source"),
    "enchanted": ("Enchanted", "modifier"),
    "spectral": ("Spectral", "modifier"),
    "cosmic": ("Cosmic", "modifier"),
    "ancient": ("Ancient", "modifier"),
    "spell": ("Spell", "object"),
    "wand": ("Wand", "object"),
    "fireball": ("Fireball", "object"),
    "tail": ("Tail", "detail"),
    "bright": ("Bright", "detail"),
    "deep": ("Deep", "detail"),
    "soft": ("Soft", "detail"),
    "distant": ("Distant", "modifier"),
    "hum": ("Hum", "detail"),
    "rumble": ("Rumble", "detail"),
    # Device / mic tokens (exact, stable)
    "MKH8040": ("MKH8040", "detail"),
    "CS-3e": ("CS-3e", "detail"),
    "CUX-100K": ("CUX-100K", "detail"),
    "Geofon": ("Geofon", "detail"),
    "MasterMix": ("MasterMix", "detail"),
    "MKIII": ("MKIII", "detail"),
    "CO-100K": ("CO-100K", "detail"),
    "beta": ("Beta", "detail"),
    "demo": ("Demo", "detail"),
    "preview": ("Preview", "detail"),
    "draft": ("Draft", "detail"),
    "wip": ("WIP", "detail"),
    "sample": ("Sample", "detail"),
    "perspective": ("Perspective", "modifier"),
    "alternate": ("Alternate", "detail"),
    "rough": ("Rough", "detail"),
    "temp": ("Temp", "detail"),
    "v2": ("V2", "detail"),
    "v3": ("V3", "detail"),
    "20250327": ("20250327", "detail"),
}

STRESS_PHRASE_MAPPINGS: dict[str, tuple[str, str]] = {
    "版本": ("Version", "detail"),
    "版本号": ("Version", "detail"),
    "样本": ("Sample", "detail"),
    "太怪": ("Weird", "detail"),
    "太长": ("Too Long", "detail"),
    "更远": ("Farther", "modifier"),
    "更短": ("Shorter", "detail"),
    "乱七八糟": ("Messy", "detail"),
    "不好听": ("Bad Sound", "detail"),
    "测试样本": ("Test Sample", "detail"),
    "不要用": ("Do Not Use", "modifier"),
    "请忽略": ("Please Ignore", "modifier"),
    "听起来像": ("Sounds Like", "modifier"),
    "听起来": ("Sounds Like", "modifier"),
    "这个": ("This", "modifier"),
    "不要": ("Do Not", "modifier"),
    "临时": ("Temp", "detail"),
}

SKIP_GROUPS = frozenset({"压力/噪音输入", "旧治理/回归样本"})
SKIP_UNKNOWNS = frozenset()


def split_camel(token: str) -> str:
    return re.sub(r"([a-z0-9])([A-Z])", r"\1 \2", token)


def lookup_v02_mapping(unknown: str, suggestion: str = "") -> tuple[str, str] | None:
    if unknown in V02_MAPPINGS:
        return V02_MAPPINGS[unknown]
    if unknown in SKIP_UNKNOWNS:
        return None
    if re.fullmatch(r"[A-Za-z][A-Za-z0-9+\-]*", unknown):
        if suggestion:
            for word in suggestion.split():
                if word.casefold() == unknown.casefold():
                    slot = _slot_for_english(word)
                    return word, slot
        spaced = split_camel(unknown)
        if spaced != unknown:
            slot = _slot_for_english(spaced.split()[0])
            return spaced, slot
        slot = _slot_for_english(unknown)
        return unknown, slot
    return None


def _slot_for_english(token: str) -> str:
    from glossary.fx_slots import infer_slot

    key = token.casefold().split()[0]
    slot = infer_slot(key, hint=token)
    allowed = {
        "action",
        "material",
        "object",
        "source",
        "motion",
        "detail",
        "modifier",
        "unknown",
    }
    return slot if slot in allowed else "detail"
